### ISSUE TITLE
'ConvexHull' does not contain a definition for 'Create'

### ISSUE THREAD

**Issue by meckzqz** [HiddenMonk/Unity3DCustomCharacterControllerCapsuleCollisionDetection#2]
Opening this repository in Unity 2019.3.12f1 yields an error on line 30 of ConvexHullGenerator.cs. A static method called Create on ConvexHull is being used, but it does not exist.

**Comment by meckzqz** [comment]
`var hull = MIConvexHull.ConvexHull.Create(verts, .000001f);`

Perhaps this will fix the issue?

**Comment by HiddenMonk** [comment]
Ah yes, thank you =).
The reason I didnt have the error on my end is because I apparently had the class named differently, so  it didnt have trouble knowing which ConvexHull static class to use.
